version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "PrimeiraFuncaoSamStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ae6ouhhtix2a"
s3_prefix = "PrimeiraFuncaoSamStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
